#!/bin/bash
module purge
module use /projects/community/modulefiles
module load intel/17.0.4 python/3.8.5-gc563

for i in {1..200}
  do cd ${i}
  phonopy --symmetry -c POSCAR
  cd .. 
done > SYMM.out

for i in {1..200}
  do cd ${i}
  sed -i '/generated by phonopy/c\Si64' BPOSCAR
  cd ..
done

echo 'Symmetry transformation done !'
